### ISSUE TITLE
Enclosure Plugin temperature control

### ISSUE THREAD

**Issue by Horci** [crysxd/OctoApp-Plugin#25]
I would like to control my enclosure temperature via OctoApp. This is a DIY heater, which managed by the enclosure plugin by a simple relay and a control temperature and humidity sensor. I can set it up from the WebUI (Enclosure plugin control tab), or send gcode before print (https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/G-CODE-Control), but I would like to control it from OctoApp. 

Is there a way to implement this feature?

Regards,

**Comment by crysxd** [comment]
At the moment the Enclosure Plugin is read-only. I would need to investigate how to change the temperature there because it's not via the "normal" temperature controls of OctoPrint. 

I created a matching ticket in the main project, but I'm not sure when I'll have time to tackle this: https://gitlab.com/realoctoapp/octoapp/-/issues/2210

In the meantime, you can send the Gcode via OctoApp's terminal and use some tricks:

- After you send a command it will appear as a shortcut
- Press the shortcut for 2 seconds and pin it as well as give it a proper name
- To show the shortcuts during prints go to main menu > Settings > OctoApp Lab > Terminal during print
